export enum ExceptionType {
    ERROR = 'ERROR',
    WRONG_DATA = 'WRONG_DATA',
    UNAUTHORIZED = 'UNAUTHORIZED',
    NOT_FOUND = 'NOT_FOUND',
    CONFLICT = 'CONFLICT',
    FORBIDDEN = 'FORBIDDEN',
}
